
language: php

php:
  - 7.1

matrix:
  fast_finish: true

before_install:
  # install mysql-server
  - sudo apt-get install -y mysql-server

install:
  # run composer
  - composer install

#before_script:

script: phpunit --configuration ./phpunit.xml

deploy:
  on:
    tags: true